// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG-CPcdJdJWG9Fbh_pD6a8R3K4ZzrPaVk',
    appId: '1:732295032278:web:014f438be2500361328877',
    messagingSenderId: '732295032278',
    projectId: 'octopus-40',
    authDomain: 'octopus-40.firebaseapp.com',
    storageBucket: 'octopus-40.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC70jNc4jgsVLERHp69urxvYJdzTr3Lnk4',
    appId: '1:732295032278:android:fa4126c7ad5f84c3328877',
    messagingSenderId: '732295032278',
    projectId: 'octopus-40',
    storageBucket: 'octopus-40.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNLElDxdLLKmcBzsiyAgQJoV3mbfWYv10',
    appId: '1:732295032278:ios:c216b762e47c9ff2328877',
    messagingSenderId: '732295032278',
    projectId: 'octopus-40',
    storageBucket: 'octopus-40.appspot.com',
    iosClientId: '732295032278-6nat2i6ijflrujijpn1t3sp4kd4fcnun.apps.googleusercontent.com',
    iosBundleId: 'com.imt.mobiletraining',
  );
}
